# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11 with Maven
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run unit tests with Maven
      run: mvn -B test --file pom.xml
    - name: Scan for vulnerabilities with OWASP Dependency Check
      run: mvn dependency-check:check
    - name: Scan for vulnerabilities with Sonatype DepShield
      run: mvn verify -Ddepshield.failBuild=false
    - name: Scan for code smells with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        organization: <your-organization-key>
        project: <your-project-key>
        token: ${{ secrets.SONAR_TOKEN }}
        scanner: 'sonar-scanner-cli'
        options: '-Dsonar.qualitygate.wait=true'
